//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEmployee.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplSkill
    {
        public int id { get; set; }
        public Nullable<int> empId { get; set; }
        public string skills { get; set; }
    
        public virtual emplDetail emplDetail { get; set; }
    }
}
