//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEmployee.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emplDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emplDetail()
        {
            this.emplPayrolls = new HashSet<emplPayroll>();
            this.emplSkills = new HashSet<emplSkill>();
        }

        [Required(ErrorMessage = "Required")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string lastName { get; set; }
        
        public int empId { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> birthDate { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string email { get; set; }
        [Required(ErrorMessage = "Required")]

        public Nullable<System.DateTime> employementDate { get; set; }
        [Required(ErrorMessage = "Required")]
        public string address { get; set; }
        [Required(ErrorMessage = "Required")]
        public string city { get; set; }
        [Required(ErrorMessage = "Required")]
        public string state { get; set; }
        [Required(ErrorMessage = "Required")]
        public string country { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emplPayroll> emplPayrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emplSkill> emplSkills { get; set; }
    }
}
